"""LoRA training facade for few-shot identity preservation."""

from __future__ import annotations

from dataclasses import asdict
from pathlib import Path
import random
from typing import Iterable, List, Optional

from .config import LoraConfig, save_json
from .dataset import FewShotIdentityDatasetBuilder, TrainingSample
from .validation import validate_lora_config


class LoraTrainer:
    """Prepare and run a LoRA fine-tuning job.

    The default backend writes a manifest that mirrors real training inputs.
    Replace ``_run_real_training`` with an Accelerate/Diffusers training loop
    when model dependencies and GPU resources are available.
    """

    def __init__(self, config: Optional[LoraConfig] = None, dataset_builder: Optional[FewShotIdentityDatasetBuilder] = None):
        self.config = config or LoraConfig()
        self.dataset_builder = dataset_builder or FewShotIdentityDatasetBuilder()

    def train(self, image_paths: Iterable[str], trigger_token: str = "fan_person") -> Path:
        validate_lora_config(self.config)
        samples = self.dataset_builder.build(image_paths, role=trigger_token)
        prepared = self._prepare_captions(samples)
        output_dir = Path(self.config.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        manifest = {
            "status": "mock_trained",
            "trigger_token": trigger_token,
            "config": asdict(self.config),
            "samples": prepared,
            "adapter_path": str(output_dir / "adapter_model.safetensors"),
            "notes": [
                "This manifest is generated by the offline trainer.",
                "Connect Diffusers/Accelerate in LoraTrainer._run_real_training for production.",
            ],
        }
        save_json(output_dir / "training_manifest.json", manifest)
        (output_dir / "adapter_model.safetensors").write_text(
            "placeholder adapter weights; replace with real LoRA weights\n",
            encoding="utf-8",
        )
        return output_dir / "training_manifest.json"

    def _prepare_captions(self, samples: List[TrainingSample]) -> List[dict]:
        rng = random.Random(1234)
        prepared = []
        for sample in samples:
            caption = self.dataset_builder.apply_prompt_dropout(sample.caption, self.config.prompt_dropout, rng)
            caption = self.dataset_builder.perturb_tags(caption, self.config.tag_noise, rng)
            prepared.append(
                {
                    "image_path": sample.image_path,
                    "caption": caption,
                    "decoupled_tags": asdict(sample.tags),
                }
            )
        return prepared

    def _run_real_training(self, prepared_samples: List[dict]) -> None:
        """Production hook for Diffusers/Accelerate.

        Pseudocode:
          - load SDXL or HunyuanDiT pipeline
          - inject LoRA modules with rank/alpha from ``self.config``
          - tokenize captions with prompt dropout already applied
          - train UNet/DiT adapter layers for ``max_steps``
          - save adapter weights as ``adapter_model.safetensors``
        """

        raise NotImplementedError("Install full dependencies and implement backend-specific training here.")
